export default {
  filename: ".changeset/README.md",
  template: `# Changesets

This folder has been automatically generated by [changesets](https://github.com/changesets/changesets).

Run \`pnpm changeset\` to describe a change, then \`pnpm version-packages\` to apply
the pending changesets: versions are bumped and each package's CHANGELOG.md is written.

Everything here is private by default (\`"access": "restricted"\`), so nothing is
published to npm. Add a \`release\` script if that changes.
`,
};
