export default {
  filename: ".changeset/README.md",
  template: `# Changesets

This folder has been automatically generated by [changesets](https://github.com/changesets/changesets).

Run \`pnpm changeset\` to describe a change, then \`pnpm version-packages\` to apply
the pending changesets: versions are bumped and each package's CHANGELOG.md is written.

\`pnpm release\` builds and runs \`changeset publish\`. Every package starts private,
so that publishes nothing until you drop \`"private": true\` from one and set
\`"access": "public"\` here.
`,
};
